default: &default
  adapter: postgresql
  encoding: unicode
  database: food-delivery
  username: gocomet
  password: <%= ENV.fetch("LIBRARY_DATABASE_PASSWORD") %>
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food-delivery
  username: gocomet
  password: <%= ENV.fetch("LIBRARY_DATABASE_PASSWORD") %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: library_test

production:
  primary: &primary_production
    <<: *default
    database: food-delivery
    username: gocomet
    password: <%= ENV.fetch("LIBRARY_DATABASE_PASSWORD")  %>
  cache:
    <<: *primary_production
    database: library_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: library_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: library_production_cable
    migrations_paths: db/cable_migrate